#!/bin/sh
rm -f manual.aux manual.dvi manual.idx manual.ilg manual.ind manual.lab manual.log manual.six manual.toc
tex manual
../../../doc/manualindex manual
tex manual
mkdir -p ../htm
../../../etc/convert.pl -c -i -u -n CaratInterface . ../htm
pdftex manual

